## 1. Split This String

In [6]:
str="Hi there Among Us"

In [7]:
print(str.split(" "))

['Hi', 'there', 'Among', 'Us']


## 2. Use format() to print the following
## Output should be: The diameter of the Earth is 12742 kilometers

In [8]:
planet="jupiter"
dia=12742

In [9]:
print("The diameter of {Planet} is {dia} kilometers.".format(Planet=planet,dia=dia))

The diameter of jupiter is 12742 kilometers.


## 3. In This Nest Dictionary, Grab The Word, "Hello"

In [10]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [11]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


## Numpy

In [12]:
import numpy as np

## 4.1 Create an array of 10 zeros?

## 4.2 Create an array of 10 fives?

In [13]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## 5. Create an array of all the even integers from 20 to 35

In [17]:
np.arange(20,35)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [24]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])


In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 5, 6])

## Pandas

## 3. Create a dataframe with 3 rows and 3 columns

In [26]:
import pandas as pd

In [28]:
data=[["Zhask",12],["Aurius",14],["Flemin",10]]

In [29]:
pd.DataFrame(data)

0   1
0   Zhask  12
1  Aurius  14
2  Flemin  10

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [31]:
pd.date_range(start="1/1/2023",end="10/2/2023")

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

## 10. Create 2D list to DataFrame
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [32]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [33]:
pd.DataFrame(lists)

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24